### ISSUE TITLE
add option to unselect MSS images for LLR composite step

### ISSUE THREAD

**Issue by acocac** [jdbcode/LandsatLinkr#1]
For those areas where MSS L1T images are not available, it will be helpful an option in the mixel function which permit to select that there is not a folder with MSS images.

**Comment by jdbcode** [comment]
Great idea! I've made the change in release 0.2.5-beta. To download and install please visit:
http://landsatlinkr.jdbcode.com/download.html
I did a small test and it worked, please help me test it further and send any errors messages you get.
