### ISSUE TITLE
Error: package ‘LandsatLinkr’ was installed before R 4.0.0: please re-install it

### ISSUE THREAD

**Issue by PratyushTripathy** [jdbcode/LandsatLinkr#10]
As suggested on the [Guide](http://jdbcode.github.io/LandsatLinkr/guide.html#install_landsatlinkr) page, I used all the three commands in sequence to install the package. However, it looks like the SDMTools package is not installed. On Googling I found that the SDMTools package is no longer available on CRAN. I found an alternative solution [here](https://stackoverflow.com/questions/60415059/r-cant-install-sdmtools-for-r-version-3-6-2). Now, SDMTools installation is complete--I checked the installation by calling the library. Installing LandsatLinkr says `package ‘LandsatLinkr’ successfuly unpacked and MD5 sums checked`, but when I call LandsatLink, it says:

`Error: package or namespace load failed for ‘LandsatLinkr’: package ‘LandsatLinkr’ was installed before R 4.0.0: please re-install it`
![image](https://user-images.githubusercontent.com/29382796/125277554-32316c80-e32f-11eb-8e8d-fee76709b557.png)

To fix this, I tried the solution given [here](https://stackoverflow.com/questions/63390194/package-xxx-was-installed-before-r-4-0-0-please-re-install-it), but it doesn't work. I uninstalled all packages and re-installed them, manual version of the same solution, but no luck so far.

My specs from a fresh R session:
<img width="503" alt="r_Env" src="https://user-images.githubusercontent.com/29382796/125275689-f7c6d000-e32c-11eb-837f-c4472fb942be.PNG">

Am I doing something fundamentally wrong?

**Comment by jdbcode** [comment]
@PratyushTripathy thanks for your interest in LandsatLinkr. Unfortunately, the package is quite stale and will likely not work without updates to dependencies and code. My apologies for not having a message as such on the README. I've just added one:

⚠️ _**This repository is no longer in development and is not supported**_ ⚠️

_You'll likely find that unmaintained dependencies and versioning conflicts make
this package unusable._

_Progress is (slowly) being made on [ee-LandsatLinkr](https://github.com/gee-community/ee-LandsatLinkr),
which offers similar MSS-to-successor harmonization procedures using Google Earth Engine._

 Unfortunately, I can no longer offer help on this package.

Best regards,
Justin
