### ISSUE TITLE
create2GDAL warning

### ISSUE THREAD

**Issue by AhmadFallatah** [jdbcode/LandsatLinkr#7]
I downloaded LandsatLink 0.5 in R using

download.file("https://github.com/jdbcode/LandsatLinkr/releases/download/0.5.0-beta/LandsatLinkr_0.5.0.zip", "LandsatLinkr")

I got this Warning message after running LLR Step 6 - Composite imagery:
In create2GDAL(dataset = dataset, drivername = drivername, type = type,  :
  mvFlag=NA unsuitable for type Byte

**Comment by lewiymwenda** [comment]
Iam also running landsatlinkr version 0.5 and am encountering this problem
**Probably broken install of gdal at 'C:/PROGRA~1/GDAL/'
Error in as.Date.default(unlist(versions)) : 
  do not know how to convert 'unlist(versions)' to class “Date”**
please help

**Comment by eefjeva** [comment]
Did you ever solve this problem? I have the same problem.

**Comment by lewiymwenda** [comment]
yeah i actually found a way around it
Happens that landsatlinkr is so choosy when it comes to gdal releases you have to get the very exact release for the version you are using 
it could  also be a memory problem 
you can try clearing the R memory using this  **rm(list=ls(all=TRUE))**
just see if that works then we can try other  things

**Comment by jdbcode** [comment]
⚠️ _**This repository is no longer in development and is not supported**_ ⚠️

_You'll likely find that unmaintained dependencies and versioning conflicts make
this package unusable._

_Progress is (slowly) being made on [ee-LandsatLinkr](https://github.com/gee-community/ee-LandsatLinkr),
which offers similar MSS-to-successor harmonization procedures using Google Earth Engine._

Unfortunately, I can no longer offer help on this package.
