### ISSUE TITLE
Problems in mssunpackr.r

### ISSUE THREAD

**Issue by ludwighagelstein** [jdbcode/LandsatLinkr#9]
Hi, 
I've been trying to run the LandsatLinkr but am running into Errors in the very first step. The compressed image filename is: "LM01_L1TP_208027_19720813_20180428_01_T2.tar.gz" 

At the beginning of the mssunpackr.r Code 
  filebase = basename(file)
  year = as.numeric(substr(filebase, 10, 13))
  if(year >= 1995){
    delete_files(file, 6)
    return(0)
  }

so the year returns NA, but the year would be at "year = as.numeric(substr(filebase, **18, 21**))"
If I change that I get Error in file(file, "rt") : invalid 'description' argument

Do I have the wrong files? Should the LandsatLinkr still work or is it outdated?

Would be very happy about help, since this could add a lot to my master thesis!

Regards,
Ludwig

**Comment by jdbcode** [comment]
Hi @ludwighagelstein. Very sorry for the slow reply. I've not worked on the project in a long time and I've visited it today to add a message closing it down:

⚠️ _**This repository is no longer in development and is not supported**_ ⚠️

_You'll likely find that unmaintained dependencies and versioning conflicts make
this package unusable._

_Progress is (slowly) being made on [ee-LandsatLinkr](https://github.com/gee-community/ee-LandsatLinkr),
which offers similar MSS-to-successor harmonization procedures using Google Earth Engine._

Unfortunately, I can no longer offer help on this package.
